# Generated by Django 5.2.2 on 2025-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorimage',
            options={'ordering': ['order'], 'verbose_name': 'Rang rasmi', 'verbose_name_plural': 'Rang rasmlari'},
        ),
        migrations.AddField(
            model_name='colorimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
